version: '3.8'

services:
  kite-server:
    build: .
    restart: always
    volumes:
    - /data/kite-server:/kite-server/config
    ports:
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
      - target: 9080
        published: 9080
        protocol: tcp
        mode: host
    depends_on:
      - rethinkdb

  rethinkdb:
    image: rethinkdb:latest
    restart: always
    volumes:
    - /data/rethinkdb:/data
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 28015
        published: 28015
        protocol: tcp
        mode: host

volumes:
  kite-server:
  rethinkdb: