version: '3.2'

services:
  kite-server:
    build: .
    ports:
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    volumes:
    - /data/redis:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "ch4ng3-m3"]

volumes:
  redis:
